'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('thuyenvien_chungchi', [
      {
        id_thuyenvien: 1,
        id_chungchi: 1,
        sohieuchungchi: 'C7381916',
        ngaycap: new Date('2019/05/27'),
        ngayhethan: new Date('2029/05/27'),
        noicap: 'Việt Nam',
        xeploai: 'KháKhá',
        file: '',
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 1,
        id_chungchi: 2,
        sohieuchungchi: 'HPG-05861',
        ngaycap: new Date('2006/10/20'),
        ngayhethan: new Date('2026/10/20'),
        noicap: 'VIET NAM ',
        xeploai: 'Khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 1,
        id_chungchi: 3,
        sohieuchungchi: 'G2059.SE1',
        ngaycap: new Date('2023/08/16'),
        ngayhethan: new Date('2028/08/16'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 1,
        id_chungchi: 4,
        sohieuchungchi: 'Đ009594/BST-VMUC',
        ngaycap: new Date('2022/01/27'),
        ngayhethan: new Date('2027/01/27'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 1,
        id_chungchi: 7,
        sohieuchungchi: 'Đ029496/SCR-VMUC',
        ngaycap: new Date('2023/08/07'),
        ngayhethan: new Date('2028/08/07'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
       {
        id_thuyenvien: 1,
        id_chungchi: 5,
        sohieuchungchi: 'Đ029500/AFF-VMUC',
        ngaycap: new Date('2023/08/07'),
        ngayhethan: new Date('2028/08/07'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
        {
        id_thuyenvien: 1,
        id_chungchi: 6,
        sohieuchungchi: 'Đ029505/MFC-VMUC',
        ngaycap: new Date('2023/08/07'),
        ngayhethan: new Date('2028/01/27'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 1,
        id_chungchi: 16,
        sohieuchungchi: 'Đ009594/BST-VMUC',
        ngaycap: new Date('2022/01/27'),
        ngayhethan: new Date('2027/01/27'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 1,
        id_chungchi: 17,
        sohieuchungchi: 'Đ025594/SSD-VMUC',
        ngaycap: new Date('2022/01/27'),
        ngayhethan: new Date('2027/01/27'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
        {
        id_thuyenvien: 1,
        id_chungchi: 13,
        sohieuchungchi: 'Đ029511/ERM-VMUC',
        ngaycap: new Date('2023/08/07'),
        ngayhethan: new Date('2028/08/07'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      //thuyen vien 2
      {
        id_thuyenvien: 2,
        id_chungchi: 1,
        sohieuchungchi: 'C9852500',
        ngaycap: new Date('2021/11/08'),
        ngayhethan: new Date('2031/11/08'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 2,
        id_chungchi: 2,
        sohieuchungchi: 'HPG-36286-01',
        ngaycap: new Date('2013/11/31'),
        ngayhethan: new Date('2023/11/31'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 2,
        id_chungchi: 3,
        sohieuchungchi: 'A7270.DO1',
        ngaycap: new Date('2020/04/13'),
        ngayhethan: new Date('2025/04/13'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 2,
        id_chungchi: 4,
        sohieuchungchi: 'G5526/BST-CD.I',
        ngaycap: new Date('2023-03-16'),
        ngayhethan: new Date('2028-03-16'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 2,
        id_chungchi: 7,
        sohieuchungchi: 'A4402.PS/BNHP',
        ngaycap: new Date('2020-03-12'),
        ngayhethan: new Date('2025-03-12'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 2,
        id_chungchi: 5,
        sohieuchungchi: 'A2730.AF/BNHP',
        ngaycap: new Date('2020-04-28'),
        ngayhethan: new Date('2025-04-28'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 2,
        id_chungchi: 6,
        sohieuchungchi: 'A2672.MF/BNHP',
        ngaycap: new Date('2020-04-28'),
        ngayhethan: new Date('2025-04-28'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 2,
        id_chungchi: 16,
        sohieuchungchi: 'B4861.SA/BNHP',
        ngaycap: new Date('2021-09-15'),
        ngayhethan: new Date('2026-09-15'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 2,
        id_chungchi: 17,
        sohieuchungchi: 'C2131.SD/BNHP',
        ngaycap: new Date('2023-03-13'),
        ngayhethan: new Date('2028-03-13'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 2,
        id_chungchi: 12,
        sohieuchungchi: '2332-20/VMTC',
        ngaycap: new Date('2020-03-20'),
        ngayhethan: new Date('2025-03-20'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 2,
        id_chungchi: 11,
        sohieuchungchi: 'A7492/HP.G',
        ngaycap: new Date('2020-04-23'),
        ngayhethan: new Date('2025-04-15'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 2,
        id_chungchi: 8,
        sohieuchungchi: '2032-20/VMTC',
        ngaycap: new Date('2020-03-07'),
        ngayhethan: new Date('2025-03-07'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 2,
        id_chungchi: 9,
        sohieuchungchi: '2055R-20/VMTC',
        ngaycap: new Date('2020-03-10'),
        ngayhethan: new Date('2025-03-10'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      //thuyen vien 3
      {
        id_thuyenvien: 3,
        id_chungchi: 1,
        sohieuchungchi: 'C1184090',
        ngaycap: new Date('2015-12-11'),
        ngayhethan: new Date('2025-12-11'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 3,
        id_chungchi: 2,
        sohieuchungchi: 'T0015095',
        ngaycap: new Date('2016-01-18'),
        ngayhethan: new Date('2021-01-18'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      
      {
        id_thuyenvien: 3,
        id_chungchi: 3,
        sohieuchungchi: 'G5441.DO1',
        ngaycap: new Date('2021-12-31'),
        ngayhethan: new Date('2026-12-31'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 3,
        id_chungchi: 7,
        sohieuchungchi: 'A6967.PS/BNHP',
        ngaycap: new Date('2021-02-19'),
        ngayhethan: new Date('2026-02-19'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 3,
        id_chungchi: 5,
        sohieuchungchi: 'A6967.PS/BNHP',
        ngaycap: new Date('2021-02-19'),
        ngayhethan: new Date('2026-02-19'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 3,
        id_chungchi: 5,
        sohieuchungchi: 'A3971.AF/BNHP',
        ngaycap: new Date('2021-02-19'),
        ngayhethan: new Date('2026-02-19'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 3,
        id_chungchi: 6,
        sohieuchungchi: 'A3877.MF/BNHP',
        ngaycap: new Date('2021-02-19'),
        ngayhethan: new Date('2026-02-19'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 3,
        id_chungchi: 16,
        sohieuchungchi: 'B3052.SA/BNHP',
        ngaycap: new Date('2021-03-10'),
        ngayhethan: new Date('2026-03-10'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 3,
        id_chungchi: 17,
        sohieuchungchi: 'A10602.SD/BNHP',
        ngaycap: new Date('2021-03-10'),
        ngayhethan: new Date('2026-03-10'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 3,
        id_chungchi: 15,
        sohieuchungchi: '1674.SO/BNHP',
        ngaycap: new Date('2021-02-19'),
        ngayhethan: new Date('2026-02-19'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 3,
        id_chungchi: 14,
        sohieuchungchi: 'A264.ED/BNHP',
        ngaycap: new Date('2021-02-19'),
        ngayhethan: new Date('2026-02-19'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 3,
        id_chungchi: 12,
        sohieuchungchi: '4499.BM/BNHP',
        ngaycap: new Date('2024-03-05'),
        ngayhethan: new Date('2029-03-05'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 3,
        id_chungchi: 11,
        sohieuchungchi: 'A11730/HP.G',
        ngaycap: new Date('2022-03-21'),
        ngayhethan: new Date('2027-03-13'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 3,
        id_chungchi: 8,
        sohieuchungchi: '2525.RD/BNHP',
        ngaycap: new Date('2021-02-19'),
        ngayhethan: new Date('2026-02-19'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id_thuyenvien: 3,
        id_chungchi: 9,
        sohieuchungchi: 'A259.AR/BNHP',
        ngaycap: new Date('2021-02-19'),
        ngayhethan: new Date('2026-02-19'),
        noicap: 'VIET NAM',
        xeploai: 'khá',
        file: null,
        createdAt: new Date(),
        updatedAt: new Date()
      },
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('thuyenvien_chungchi', null, {});
  }
};
